Feature/coe parametrization (#1)
orocos/rtt_soem pull request #10
Opened 2016-10-14 13:53 UTC by MagnaboscoL

* Each slave can be parametrized differently since its CoE parameters are loaded from the file soem.cpf.
* Fix the ec_state unknown issue in the Task Browser
* Fix the master/slaves state mismatch

@smits PTAL

2016-10-17 12:44 UTC, smits commented on soem_master/soem_master_component.cpp
> +
Why do we put this here? Can this COE writing not happen as inside the specific driver's configure function that will be called on https://github.com/orocos/rtt_soem/pull/10/files#diff-c640e145ce9eefcd6c669e8897228c3bL112 .  This is exactly why that function is there.

2016-10-17 12:48 UTC, smits commented on soem_master/soem_master_component.cpp
> +
The comment is not really clear to me.  Shouldn't https://github.com/orocos/rtt_soem/pull/10/files#diff-c640e145ce9eefcd6c669e8897228c3bR204 already take care of this?

2016-10-17 12:48 UTC, smits commented on soem_master/soem_master_component.cpp
> +
Same here.

2016-10-17 12:57 UTC, smits requested changes
I'm not convinced that the CoE reads and writes should happen here, can't we move that into the configure function of each respective driver?

2016-10-17 12:57 UTC, smits commented on soem_master/soem_master_component.cpp
> +int SoemMasterComponent::writeCoeSDO(addressInfo* address,bool completeAccess,int size,void* data)
spaces!  rename to writeCoeSdo.

2016-10-17 12:57 UTC, smits commented on soem_master/soem_master_component.cpp
> +int SoemMasterComponent::readCoeSDO(addressInfo* address,bool completeAccess,int* size,void* data)
spaces! rename to readCoeSdo

2016-10-17 12:57 UTC, smits commented on soem_master/soem_master_component.h
> +struct addressInfo
Please rename to AddressInfo

2016-10-17 12:57 UTC, smits commented on soem_master/soem_master_component.h
> +    int   writeCoeSDO(addressInfo* address,bool completeAccess,int size,void* data);
Can't we make this const addressInfo& ?

2016-10-17 12:57 UTC, smits commented on soem_master/soem_master_component.h
> +    int   readCoeSDO(addressInfo* address,bool completeAccess,int* size,void* data);
Same here.

2016-10-17 12:57 UTC, smits commented on soem_master/soem_master_types.hpp
> +  int slavePosition;
rename to slave_position

2016-10-17 12:57 UTC, smits commented on soem_master/soem_master_types.hpp
> +  int subIndex;
sub_index

2016-10-17 12:57 UTC, smits commented on soem_master/soem_master_types.hpp
> +  bool completeAccess;
complete_access

2016-10-17 12:57 UTC, smits commented on soem_master/soem_master_types.hpp
> +struct parameter
please put this in a namespace (rtt_soem) and rename to Parameter

2016-10-17 12:57 UTC, smits commented on soem_master/soem_master_component.cpp
> +    RTT::types::Types()->addType(new types::SequenceTypeInfo< std::vector<parameter> >("std.vector<parameter>"));
Shouldn't we move this into a plugin instead of here? Otherwise we'll add this type for every SoemMasterComponent instance that we create.

2016-10-17 13:06 UTC, MagnaboscoL commented on soem_master/soem_master_component.cpp
> +
ec_statecheck() if called with the first argument set to 0 does not update the state of the slaves in the structure ec_slave[] even if the slaves' state has changed properly. 
Looking the code of the function you can see that "ec_slave[slave].state = rval;" is not done for every slave as it should be when called with the first argument set to 0.

This cause that when the User call for example "Slave_1001.getState()" the retrieved state is different from the real one.

2016-10-17 13:08 UTC, MagnaboscoL commented on soem_master/soem_master_component.cpp
> +
As written above unfortunately ec_statecheck() does not update the state of all the slaves but only the "master state" contained in ec_slave[0].state

2016-10-17 13:28 UTC, MagnaboscoL commented on soem_master/soem_master_component.cpp
> +    RTT::types::Types()->addType(new types::SequenceTypeInfo< std::vector<parameter> >("std.vector<parameter>"));
About the operations "writeCoeSDO" and  "readCoeSDO" they are common to all the slaves that have a mailbox and support the CoE protocol and for all these slaves it is done at the same way. 
So yes we can move them to the plugins, but then we could have a lot of plugins that will add the same operation that will be done exactly in the same way.
The idea was "if the operation is exactly the same for all the slaves then it could be in the soem_master component" but if preferred we can move them.

About the property "SlavesCoEParameters" it was placed here because I found useful be able to read the parameters from the soem.cpf. 
Can every plugin read its own .cpf ? If yes, it would be better to move them to the plugins. 
Maybe you have in mind a different approach for the parametrization that would work for plugins too.

2016-10-17 13:32 UTC, MagnaboscoL commented on soem_master/soem_master_component.cpp
> +
Of course the CoE writing could happen in the driver's configure function (and I would have preferred that) but was placed here since the property "slavesCoeParameters" is a master's property.
As described above I think that the whole matter is totally depending on the parameterization approach so any suggestion to improve that is welcome.

2016-10-17 18:50 UTC, smits commented on soem_master/soem_master_component.cpp
> +
Ok, I did not realise that, could we also add Error logging in case the expected state was not reached.

2016-10-17 18:50 UTC, smits commented on soem_master/soem_master_component.cpp
> +
Adding Error logging in case a specific slave would not reach the expected state would be nice here as well

2016-10-18 15:35 UTC, MagnaboscoL commented
Ok,
I close this pull request and I will open another one with the marked issues fixed.

Thanks

2016-10-18 15:35 UTC, closed without merging